export const FINANCE_FETCH_REQUEST = 'finance/FETCH_REQUEST';
export const FINANCE_FETCH_SUCCESS = 'finance/FETCH_SUCCESS';
export const FINANCE_FETCH_ERROR = 'finance/FETCH_ERROR';

export const TOTAL_BALANCE_FETCH_SUCCESS = 'finance/TOTAL_BALANCE_FETCH_SUCCESS';
export const TOTAL_BALANCE_FETCH_ERROR = 'finance/TOTAL_BALANCE_FETCH_ERROR';
