export const FINANCE_FETCH_REQUEST = 'finance/FETCH_REQUEST';
export const FINANCE_FETCH_SUCCESS = 'finance/FETCH_SUCCESS';
export const FINANCE_FETCH_ERROR = 'finance/FETCH_ERROR';
export const ADD_TO_FINANCE = 'finance/ADD_TO_FINANCE';

export const TOTAL_BALANCE_FETCH_SUCCESS = 'finance/TOTAL_BALANCE_FETCH_SUCCESS';
export const TOTAL_BALANCE_FETCH_ERROR = 'finance/TOTAL_BALANCE_FETCH_ERROR';

export const TYPE_TOTAL_BALANCE_FETCH_SUCCESS = 'finance/TYPE_TOTAL_BALANCE_FETCH_SUCCESS';
export const TYPE_TOTAL_BALANCE_FETCH_ERROR = 'finance/TYPE_TOTAL_BALANCE_FETCH_ERROR';

export const TOTAL_COST_FETCH_SUCCESS = 'finance/TOTAL_COST_FETCH_SUCCESS';
export const TOTAL_COST_FETCH_ERROR = 'finance/TOTAL_COST_FETCH_ERROR';

export const TOTAL_INCOME_FETCH_SUCCESS = 'finance/TOTAL_INCOME_FETCH_SUCCESS';
export const TOTAL_INCOME_FETCH_ERROR = 'finance/TOTAL_INCOME_FETCH_ERROR';
